USE [Bonava Objects]
GO

-- Base Table
INSERT INTO [Bonava-Dev].[dbo].[CRONUS Россия ЗАО$Location$437dbf0e-84ff-417a-965d-ed2bb9650972]
           ([Code]
           ,[Name]
           ,[Default Bin Code]
           ,[Name 2]
           ,[Address]
           ,[Address 2]
           ,[City]
           ,[Phone No_]
           ,[Phone No_ 2]
           ,[Telex No_]
           ,[Fax No_]
           ,[Contact]
           ,[Post Code]
           ,[County]
           ,[E-Mail]
           ,[Home Page]
           ,[Country_Region Code]
           ,[Use As In-Transit]
           ,[Require Put-away]
           ,[Require Pick]
           ,[Cross-Dock Due Date Calc_]
           ,[Use Cross-Docking]
           ,[Require Receive]
           ,[Require Shipment]
           ,[Bin Mandatory]
           ,[Directed Put-away and Pick]
           ,[Default Bin Selection]
           ,[Outbound Whse_ Handling Time]
           ,[Inbound Whse_ Handling Time]
           ,[Put-away Template Code]
           ,[Use Put-away Worksheet]
           ,[Pick According to FEFO]
           ,[Allow Breakbulk]
           ,[Bin Capacity Policy]
           ,[Open Shop Floor Bin Code]
           ,[To-Production Bin Code]
           ,[From-Production Bin Code]
           ,[Adjustment Bin Code]
           ,[Always Create Put-away Line]
           ,[Always Create Pick Line]
           ,[Special Equipment]
           ,[Receipt Bin Code]
           ,[Shipment Bin Code]
           ,[Cross-Dock Bin Code]
           ,[To-Assembly Bin Code]
           ,[From-Assembly Bin Code]
           ,[Asm_-to-Order Shpt_ Bin Code]
           ,[Base Calendar Code]
           ,[Use ADCS]
           ,[Last Goods Report No_]
           ,[Last Goods Report Date]
           ,[Responsible Employee No_])
SELECT
	      SUBSTRING([Code],1,10)  -- В старой версии длина поля - 20, в текущей - 10
           ,NULL --[Name]
           ,NULL --[Default Bin Code]
           ,NULL --[Name 2]
           ,NULL --[Address]
           ,NULL --[Address 2]
           ,NULL --[City]
           ,NULL --[Phone No_]
           ,NULL --[Phone No_ 2]
           ,NULL --[Telex No_]
           ,NULL --[Fax No_]
           ,NULL --[Contact]
           ,NULL --[Post Code]
           ,NULL --[County]
           ,NULL --[E-Mail]
           ,NULL --[Home Page]
           ,NULL --[Country_Region Code]
           ,NULL --[Use As In-Transit]
           ,NULL --[Require Put-away]
           ,NULL --[Require Pick]
           ,NULL --[Cross-Dock Due Date Calc_]
           ,NULL --[Use Cross-Docking]
           ,NULL --[Require Receive]
           ,NULL --[Require Shipment]
           ,NULL --[Bin Mandatory]
           ,NULL --[Directed Put-away and Pick]
           ,NULL --[Default Bin Selection]
           ,NULL --[Outbound Whse_ Handling Time]
           ,NULL --[Inbound Whse_ Handling Time]
           ,NULL --[Put-away Template Code]
           ,NULL --[Use Put-away Worksheet]
           ,NULL --[Pick According to FEFO]
           ,NULL --[Allow Breakbulk]
           ,NULL --[Bin Capacity Policy]
           ,NULL --[Open Shop Floor Bin Code]
           ,NULL --[To-Production Bin Code]
           ,NULL --[From-Production Bin Code]
           ,NULL --[Adjustment Bin Code]
           ,NULL --[Always Create Put-away Line]
           ,NULL --[Always Create Pick Line]
           ,NULL --[Special Equipment]
           ,NULL --[Receipt Bin Code]
           ,NULL --[Shipment Bin Code]
           ,NULL --[Cross-Dock Bin Code]
           ,NULL --[To-Assembly Bin Code]
           ,NULL --[From-Assembly Bin Code]
           ,NULL --[Asm_-to-Order Shpt_ Bin Code]
           ,NULL --[Base Calendar Code]
           ,NULL --[Use ADCS]
           ,NULL --[Last Goods Report No_]
           ,NULL --[Last Goods Report Date]
           ,NULL --[Responsible Employee No_]
FROM [dbo].[test$Location];

-- Table Extension
INSERT INTO [Bonava-Dev].[dbo].[CRONUS Россия ЗАО$Location$2944687f-9cf8-4134-a24c-e21fb70a8b1a]
           ([Code]
           ,[Blocked]
           ,[Def_ Gen_ Bus_ Posting Group])
SELECT 
            SUBSTRING([Code],1,10)  -- В старой версии длина поля - 20, в текущей - 10
           ,[Blocked]
           ,[Def_ Gen_ Bus_ Posting Group]
FROM [dbo].[test$Location]