-- Base Table
INSERT INTO [Bonava-Test].[dbo].[Bonava$Location$437dbf0e-84ff-417a-965d-ed2bb9650972]
(
	[Code],
	[Name],
	[Default Bin Code],
	[Name 2],
	[Address],
	[Address 2],
	[City],
	[Phone No_],
	[Phone No_ 2],
	[Telex No_],
	[Fax No_],
	[Contact],
	[Post Code],
	[County],
	[E-Mail],
	[Home Page],
	[Country_Region Code],
	[Use As In-Transit],
	[Require Put-away],
	[Require Pick],
	[Cross-Dock Due Date Calc_],
	[Use Cross-Docking],
	[Require Receive],
	[Require Shipment],
	[Bin Mandatory],
	[Directed Put-away and Pick],
	[Default Bin Selection],
	[Outbound Whse_ Handling Time],
	[Inbound Whse_ Handling Time],
	[Put-away Template Code],
	[Use Put-away Worksheet],
	[Pick According to FEFO],
	[Allow Breakbulk],
	[Bin Capacity Policy],
	[Open Shop Floor Bin Code],
	[To-Production Bin Code],
	[From-Production Bin Code],
	[Adjustment Bin Code],
	[Always Create Put-away Line],
	[Always Create Pick Line],
	[Special Equipment],
	[Receipt Bin Code],
	[Shipment Bin Code],
	[Cross-Dock Bin Code],
	[To-Assembly Bin Code],
	[From-Assembly Bin Code],
	[Asm_-to-Order Shpt_ Bin Code],
	[Base Calendar Code],
	[Use ADCS],
	[Last Goods Report No_],
	[Last Goods Report Date],
	[Responsible Employee No_]
)
SELECT
	[Code],
    [Name],
	'' AS [Default Bin Code],
	[Name 2],
	'' AS [Address],
	'' AS [Address 2],
	'' AS [City],
	'' AS [Phone No_],
	'' AS [Phone No_ 2],
	'' AS [Telex No_],
	'' AS [Fax No_],
	'' AS [Contact],
	'' AS [Post Code],
	'' AS [County],
	'' AS [E-Mail],
	'' AS [Home Page],
	'' AS [Country_Region Code],
	[Use As In-Transit],
	0 AS [Require Put-away],
	0 AS [Require Pick],
	'' AS [Cross-Dock Due Date Calc_],
	0 AS [Use Cross-Docking],
	0 AS [Require Receive],
	0 AS [Require Shipment],
	[Bin Mandatory],
	0 AS [Directed Put-away and Pick],
	[Default Bin Selection],
	'' AS [Outbound Whse_ Handling Time],
	'' AS [Inbound Whse_ Handling Time],
	'' AS [Put-away Template Code],
	0 AS [Use Put-away Worksheet],
	0 AS [Pick According to FEFO],
	0 AS [Allow Breakbulk],
	0 AS [Bin Capacity Policy],
	'' AS [Open Shop Floor Bin Code],
	'' AS [To-Production Bin Code],
	'' AS [From-Production Bin Code],
	'' AS [Adjustment Bin Code],
	0 AS [Always Create Put-away Line],
	0 AS [Always Create Pick Line],
	0 AS [Special Equipment],
	'' AS [Receipt Bin Code],
	'' AS [Shipment Bin Code],
	'' AS [Cross-Dock Bin Code],
	'' AS [To-Assembly Bin Code],
	'' AS [From-Assembly Bin Code],
	'' AS [Asm_-to-Order Shpt_ Bin Code],
	'' AS [Base Calendar Code],
	0 AS [Use ADCS],
	0 AS [Last Goods Report No_],
	[Last Goods Report Date],
	'' AS [Responsible Employee No_]
FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$Location];

-- Table Extension
INSERT INTO [Bonava-Test].[dbo].[Bonava$Location$2944687f-9cf8-4134-a24c-e21fb70a8b1a]
(
	[Code],
	[Blocked],
	[Def_ Gen_ Bus_ Posting Group]
)
SELECT 
	[Code],
	[Blocked],
	[Def_ Gen_ Bus_ Posting Group]
FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$Location];

-- Default Dimension
INSERT INTO [Bonava-Test].[dbo].[Bonava$Default Dimension$437dbf0e-84ff-417a-965d-ed2bb9650972]
(
	[Table ID],
	[No_],
	[Dimension Code],
	[Dimension Value Code],
	[Value Posting],
	[Multi Selection Action]
)
SELECT
	[Table ID],
	[No_],
	[Dimension Code],
	[Dimension Value Code],
	[Value Posting],
	[Multi Selection Action]
FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$Default Dimension]
WHERE [Table ID] = '14' AND [Dimension Code] <> 'CP';