USE [Bonava Objects]
GO

-- Base Table
INSERT INTO [Bonava-Dev].[dbo].[CRONUS Россия ЗАО$Vendor$437dbf0e-84ff-417a-965d-ed2bb9650972]
(
	   [No_]
      ,[Name]
      ,[Search Name]
      ,[Name 2]
      ,[Address]
      ,[Address 2]
      ,[City]
      ,[Contact]
      ,[Phone No_]
      ,[Telex No_]
      ,[Our Account No_]
      ,[Territory Code]
      ,[Global Dimension 1 Code]
      ,[Global Dimension 2 Code]
      ,[Budgeted Amount]
      ,[Vendor Posting Group]
      ,[Currency Code]
      ,[Language Code]
      ,[Statistics Group]
      ,[Payment Terms Code]
      ,[Fin_ Charge Terms Code]
      ,[Purchaser Code]
      ,[Shipment Method Code]
      ,[Shipping Agent Code]
      ,[Invoice Disc_ Code]
      ,[Country_Region Code]
      ,[Blocked]
      ,[Pay-to Vendor No_]
      ,[Priority]
      ,[Payment Method Code]
      ,[Last Modified Date Time]
      ,[Last Date Modified]
      ,[Application Method]
      ,[Prices Including VAT]
      ,[Fax No_]
      ,[Telex Answer Back]
      ,[VAT Registration No_]
      ,[Gen_ Bus_ Posting Group]
      ,[Picture]
      ,[GLN]
      ,[Post Code]
      ,[County]
      ,[EORI Number]
      ,[E-Mail]
      ,[Home Page]
      ,[No_ Series]
      ,[Tax Area Code]
      ,[Tax Liable]
      ,[VAT Bus_ Posting Group]
      ,[Block Payment Tolerance]
      ,[IC Partner Code]
      ,[Prepayment _]
      ,[Partner Type]
      ,[Image]
      ,[Privacy Blocked]
      ,[Disable Search by Name]
      ,[Creditor No_]
      ,[Preferred Bank Account Code]
      ,[Cash Flow Payment Terms Code]
      ,[Primary Contact No_]
      ,[Mobile Phone No_]
      ,[Responsibility Center]
      ,[Location Code]
      ,[Lead Time Calculation]
      ,[Price Calculation Method]
      ,[Base Calendar Code]
      ,[Document Sending Profile]
      ,[Validate EU Vat Reg_ No_]
      ,[Id]
      ,[Currency Id]
      ,[Payment Terms Id]
      ,[Payment Method Id]
      ,[Over-Receipt Code]
      ,[Default Bank Code]
      ,[OKPO Code]
      ,[OKONX Code]
      ,[Customer No_]
      ,[Employee No_]
      ,[Tax Authority Code]
      ,[Full Name]
      ,[VAT Agent]
      ,[VAT Agent Prod_ Posting Group]
      ,[VAT Payment Source Type]
      ,[VAT Agent Type]
      ,[Tax Authority No_]
      ,[Vendor Type]
      ,[KPP Code]
      ,[Control Tax Organ]
      ,[Agreement Posting]
      ,[Agreement Nos_]
)
SELECT
	   [No_]
      ,NULL --[Name]
      ,NULL --[Search Name]
      ,NUll --[Name 2]
      ,NULL --[Address]
      ,NULL --[Address 2]
      ,NULL --[City]
      ,NULL --[Contact]
      ,NULL --[Phone No_]
      ,NULL --[Telex No_]
      ,NULL --[Our Account No_]
      ,NULL --[Territory Code]
      ,NULL --[Global Dimension 1 Code]
      ,NULL --[Global Dimension 2 Code]
      ,NULL --[Budgeted Amount]
      ,NULL --[Vendor Posting Group]
      ,NULL --[Currency Code]
      ,NULL --[Language Code]
      ,NULL --[Statistics Group]
      ,NULL --[Payment Terms Code]
      ,NULL --[Fin_ Charge Terms Code]
      ,NULL --[Purchaser Code]
      ,NULL --[Shipment Method Code]
      ,NULL --[Shipping Agent Code]
      ,NULL --[Invoice Disc_ Code]
      ,NULL --[Country_Region Code]
      ,NULL --[Blocked]
      ,NULL --[Pay-to Vendor No_]
      ,NULL --[Priority]
      ,NULL --[Payment Method Code]
      ,NULL --[Last Modified Date Time]
      ,NULL --[Last Date Modified]
      ,NULL --[Application Method]
      ,NULL --[Prices Including VAT]
      ,NULL --[Fax No_]
      ,NULL --[Telex Answer Back]
      ,NULL --[VAT Registration No_]
      ,NULL --[Gen_ Bus_ Posting Group]
      ,NULL --[Picture]
      ,NULL --[GLN]
      ,NULL --[Post Code]
      ,NULL --[County]
      ,NULL --[EORI Number]
      ,NULL --[E-Mail]
      ,NULL --[Home Page]
      ,NULL --[No_ Series]
      ,NULL --[Tax Area Code]
      ,NULL --[Tax Liable]
      ,NULL --[VAT Bus_ Posting Group]
      ,NULL --[Block Payment Tolerance]
      ,NULL --[IC Partner Code]
      ,NULL --[Prepayment _]
      ,NULL --[Partner Type]
      ,NULL --[Image]
      ,NULL --[Privacy Blocked]
      ,NULL --[Disable Search by Name]
      ,NULL --[Creditor No_]
      ,NULL --[Preferred Bank Account Code]
      ,NULL --[Cash Flow Payment Terms Code]
      ,NULL --[Primary Contact No_]
      ,NULL --[Mobile Phone No_]
      ,NULL --[Responsibility Center]
      ,NULL --[Location Code]
      ,NULL --[Lead Time Calculation]
      ,NULL --[Price Calculation Method]
      ,NULL --[Base Calendar Code]
      ,NULL --[Document Sending Profile]
      ,NULL --[Validate EU Vat Reg_ No_]
      ,NULL --[Id]
      ,NULL --[Currency Id]
      ,NULL --[Payment Terms Id]
      ,NULL --[Payment Method Id]
      ,NULL --[Over-Receipt Code]
      ,NULL --[Default Bank Code]
      ,NULL --[OKPO Code]
      ,NULL --[OKONX Code]
      ,NULL --[Customer No_]
      ,NULL --[Employee No_]
      ,NULL --[Tax Authority Code]
      ,NULL --[Full Name]
      ,NULL --[VAT Agent]
      ,NULL --[VAT Agent Prod_ Posting Group]
      ,NULL --[VAT Payment Source Type]
      ,NULL --[VAT Agent Type]
      ,NULL --[Tax Authority No_]
      ,NULL --[Vendor Type]
      ,NULL --[KPP Code]
      ,NULL --[Control Tax Organ]
      ,NULL --[Agreement Posting]
      ,NULL --[Agreement Nos_]
FROM [dbo].[test$Vendor];

-- Table Extension
INSERT INTO [dbo].[CRONUS Россия ЗАО$Vendor$2944687f-9cf8-4134-a24c-e21fb70a8b1a]
           ([No_]
           ,[Vat Agent Posting Group]
           ,[Giv_ Manuf_ Location Code]
           ,[Giv_ Manuf_ Bin Code])
     /****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
      ,[No_]
      ,NULL
      ,[Giv_ Manuf_ Location Code]
      ,[Giv_ Manuf_ Bin Code]
  FROM [dbo].[test$Vendor]