USE [Bonava Objects]
GO

-- Base Table
INSERT INTO [Bonava-Dev].[dbo].[CRONUS Россия ЗАО$Inventory Setup$437dbf0e-84ff-417a-965d-ed2bb9650972]
(
	 [Primary Key]
      ,[Automatic Cost Posting]
      ,[Location Mandatory]
      ,[Item Nos_]
      ,[Automatic Cost Adjustment]
      ,[Prevent Negative Inventory]
      ,[Skip Prompt to Create Item]
      ,[Copy Item Descr_ to Entries]
      ,[Transfer Order Nos_]
      ,[Posted Transfer Shpt_ Nos_]
      ,[Posted Transfer Rcpt_ Nos_]
      ,[Copy Comments Order to Shpt_]
      ,[Copy Comments Order to Rcpt_]
      ,[Nonstock Item Nos_]
      ,[Outbound Whse_ Handling Time]
      ,[Inbound Whse_ Handling Time]
      ,[Expected Cost Posting to G_L]
      ,[Default Costing Method]
      ,[Average Cost Calc_ Type]
      ,[Average Cost Period]
      ,[Phys_ Invt_ Order Nos_]
      ,[Posted Phys_ Invt_ Order Nos_]
      ,[Item Group Dimension Code]
      ,[Inventory Put-away Nos_]
      ,[Inventory Pick Nos_]
      ,[Posted Invt_ Put-away Nos_]
      ,[Posted Invt_ Pick Nos_]
      ,[Inventory Movement Nos_]
      ,[Registered Invt_ Movement Nos_]
      ,[Internal Movement Nos_]
      ,[Item Receipt Nos_]
      ,[Posted Item Receipt Nos_]
      ,[Item Shipment Nos_]
      ,[Posted Item Shipment Nos_]
      ,[CD Header Nos_]
      ,[Posted Direct Transfer Nos_]
      ,[Copy Comments to Item Doc_]
      ,[Check Application Date]
      ,[Unit of Measure Mandatory]
      ,[Automatic Posting Date Adjmt_]
      ,[Employee No_ Mandatory]
      ,[Adjmt_ Rounding as Correction]
      ,[Enable Red Storno]
      ,[Check CD No_ Format]
      ,[TORG-13 Template Code]
      ,[Waybill 1-T Template Code]
      ,[Item Document Template Code]
      ,[Shpt_Request M-11 Templ_ Code]
      ,[TORG-16 Template Code]
      ,[INV-17 Template Code]
      ,[INV-17 Appendix Template Code]
      ,[Item Card M-17 Template Code]
      ,[Phys_Inv_ INV-3 Template Code]
      ,[Phys_Inv_ INV-19 Template Code]
      ,[TORG-29 Template Code]
)
SELECT
	 [Primary Key]
      ,NULL --[Automatic Cost Posting]
      ,NULL --[Location Mandatory]
      ,NULL --[Item Nos_]
      ,NULL --[Automatic Cost Adjustment]
      ,NULL --[Prevent Negative Inventory]
      ,NULL --[Skip Prompt to Create Item]
      ,NULL --[Copy Item Descr_ to Entries]
      ,NULL --[Transfer Order Nos_]
      ,NULL --[Posted Transfer Shpt_ Nos_]
      ,NULL --[Posted Transfer Rcpt_ Nos_]
      ,NULL --[Copy Comments Order to Shpt_]
      ,NULL --[Copy Comments Order to Rcpt_]
      ,NULL --[Nonstock Item Nos_]
      ,NULL --[Outbound Whse_ Handling Time]
      ,NULL --[Inbound Whse_ Handling Time]
      ,NULL --[Expected Cost Posting to G_L]
      ,NULL --[Default Costing Method]
      ,NULL --[Average Cost Calc_ Type]
      ,NULL --[Average Cost Period]
      ,NULL --[Phys_ Invt_ Order Nos_]
      ,NULL --[Posted Phys_ Invt_ Order Nos_]
      ,NULL --[Item Group Dimension Code]
      ,NULL --[Inventory Put-away Nos_]
      ,NULL --[Inventory Pick Nos_]
      ,NULL --[Posted Invt_ Put-away Nos_]
      ,NULL --[Posted Invt_ Pick Nos_]
      ,NULL --[Inventory Movement Nos_]
      ,NULL --[Registered Invt_ Movement Nos_]
      ,NULL --[Internal Movement Nos_]
      ,NULL --[Item Receipt Nos_]
      ,NULL --[Posted Item Receipt Nos_]
      ,NULL --[Item Shipment Nos_]
      ,NULL --[Posted Item Shipment Nos_]
      ,NULL --[CD Header Nos_]
      ,NULL --[Posted Direct Transfer Nos_]
      ,NULL --[Copy Comments to Item Doc_]
      ,NULL --[Check Application Date]
      ,NULL --[Unit of Measure Mandatory]
      ,NULL --[Automatic Posting Date Adjmt_]
      ,NULL --[Employee No_ Mandatory]
      ,NULL --[Adjmt_ Rounding as Correction]
      ,NULL --[Enable Red Storno]
      ,NULL --[Check CD No_ Format]
      ,NULL --[TORG-13 Template Code]
      ,NULL --[Waybill 1-T Template Code]
      ,NULL --[Item Document Template Code]
      ,NULL --[Shpt_Request M-11 Templ_ Code]
      ,NULL --[TORG-16 Template Code]
      ,NULL --[INV-17 Template Code]
      ,NULL --[INV-17 Appendix Template Code]
      ,NULL --[Item Card M-17 Template Code]
      ,NULL --[Phys_Inv_ INV-3 Template Code]
      ,NULL --[Phys_Inv_ INV-19 Template Code]
      ,NULL --[TORG-29 Template Code]
FROM [dbo].[test$Inventory Setup];

-- Table Extension
INSERT INTO [Bonava-Dev].[dbo].[CRONUS Россия ЗАО$Inventory Setup$2944687f-9cf8-4134-a24c-e21fb70a8b1a]
           ([Primary Key]
           ,[Temp Item Code]
           ,[Giv_ Materials Loc_ Code]
           ,[Giv_ Production Loc_ Code]
           ,[Use Giv_ Production Func_])
SELECT 
       [Primary Key]
      ,NULL --[Temp Item Code]
      ,[Giv_ Materials Loc_ Code]
      ,[Giv_ Production Loc_ Code]
      ,[Use Giv_ Production Func_]
FROM [dbo].[test$Inventory Setup]