/*

GG: Переносить через учет остатков!


delete from [dbo].[Bonava$FA Ledger Entry$437dbf0e-84ff-417a-965d-ed2bb9650972]

insert into [dbo].[Bonava$FA Ledger Entry$437dbf0e-84ff-417a-965d-ed2bb9650972]
(
      [Entry No_]
      ,[G_L Entry No_]
      ,[FA No_]
      ,[FA Posting Date]
      ,[Posting Date]
      ,[Document Type]
      ,[Document Date]
      ,[Document No_]
      ,[External Document No_]
      ,[Description]
      ,[Depreciation Book Code]
      ,[FA Posting Category]
      ,[FA Posting Type]
      ,[Amount]
      ,[Debit Amount]
      ,[Credit Amount]
      ,[Reclassification Entry]
      ,[Part of Book Value]
      ,[Part of Depreciable Basis]
      ,[Disposal Calculation Method]
      ,[Disposal Entry No_]
      ,[No_ of Depreciation Days]
      ,[Quantity]
      ,[FA No__Budgeted FA No_]
      ,[FA Subclass Code]
      ,[FA Location Code]
      ,[FA Posting Group]
      ,[Global Dimension 1 Code]
      ,[Global Dimension 2 Code]
      ,[Location Code]
      ,[User ID]
      ,[Depreciation Method]
      ,[Depreciation Starting Date]
      ,[Straight-Line _]
      ,[No_ of Depreciation Years]
      ,[Fixed Depr_ Amount]
      ,[Declining-Balance _]
      ,[Depreciation Table Code]
      ,[Journal Batch Name]
      ,[Source Code]
      ,[Reason Code]
      ,[Transaction No_]
      ,[Bal_ Account Type]
      ,[Bal_ Account No_]
      ,[VAT Amount]
      ,[Gen_ Posting Type]
      ,[Gen_ Bus_ Posting Group]
      ,[Gen_ Prod_ Posting Group]
      ,[FA Class Code]
      ,[FA Exchange Rate]
      ,[Amount (LCY)]
      ,[Result on Disposal]
      ,[Correction]
      ,[Index Entry]
      ,[Canceled from FA No_]
      ,[Depreciation Ending Date]
      ,[Use FA Ledger Check]
      ,[Automatic Entry]
      ,[Depr_ Starting Date (Custom 1)]
      ,[Depr_ Ending Date (Custom 1)]
      ,[Accum_ Depr_ _ (Custom 1)]
      ,[Depr_ _ this year (Custom 1)]
      ,[Property Class (Custom 1)]
      ,[No_ Series]
      ,[Tax Area Code]
      ,[Tax Liable]
      ,[Tax Group Code]
      ,[Use Tax]
      ,[VAT Bus_ Posting Group]
      ,[VAT Prod_ Posting Group]
      ,[Reversed]
      ,[Reversed by Entry No_]
      ,[Reversed Entry No_]
      ,[Dimension Set ID]
      ,[Employee No_]
      ,[Prepmt_ Diff_ Appln_ Entry No_]
      ,[Item No_]
      ,[Item Entry No_]
      ,[Value Entry No_]
      ,[Need Cost Posted to G_L]
      ,[Corr_ Value Entry No_]
      ,[Initial Acquisition]
      ,[FA Charge No_]
      ,[Depr_ Period Starting Date]
      ,[Depr_ Bonus]
      ,[Depr_ Bonus _]
      ,[Sales Gain Amount]
      ,[Sales Loss Amount]
      ,[Depr_ Amount w_o Normalization]
      ,[Depr_ Group Elimination]
      ,[Tax Difference Code]
      ,[Belonging to Manufacturing]
      ,[FA Type]
      ,[Depreciation Group]
      ,[Depr_ Bonus Recovery Date]
)
 SELECT 
       [Entry No_]
      ,[G_L Entry No_]
      ,[FA No_]
      ,[FA Posting Date]
      ,[Posting Date]
      ,[Document Type]
      ,[Document Date]
      ,[Document No_]
      ,[External Document No_]
      ,[Description]
      ,[Depreciation Book Code]
      ,[FA Posting Category]
      ,[FA Posting Type]
      ,[Amount]
      ,[Debit Amount]
      ,[Credit Amount]
      ,[Reclassification Entry]
      ,[Part of Book Value]
      ,[Part of Depreciable Basis]
      ,[Disposal Calculation Method]
      ,[Disposal Entry No_]
      ,[No_ of Depreciation Days]
      ,[Quantity]
      ,[FA No__Budgeted FA No_]
      ,[FA Subclass Code]
      ,[FA Location Code]
      ,[FA Posting Group]
      ,[Global Dimension 1 Code]
      ,[Global Dimension 2 Code]
      ,[Location Code]
      ,[User ID]
      ,[Depreciation Method]
      ,[Depreciation Starting Date]
      ,[Straight-Line %]
      ,[No_ of Depreciation Years]
      ,[Fixed Depr_ Amount]
      ,[Declining-Balance %]
      ,[Depreciation Table Code]
      ,[Journal Batch Name]
      ,[Source Code]
      ,[Reason Code]
      ,[Transaction No_]
      ,[Bal_ Account Type]
      ,[Bal_ Account No_]
      ,[VAT Amount]
      ,[Gen_ Posting Type]
      ,[Gen_ Bus_ Posting Group]
      ,[Gen_ Prod_ Posting Group]
      ,[FA Class Code]
      ,[FA Exchange Rate]
      ,[Amount (LCY)]
      ,[Result on Disposal]
      ,[Correction]
      ,[Index Entry]
      ,[Canceled from FA No_]
      ,[Depreciation Ending Date]
      ,[Use FA Ledger Check]
      ,[Automatic Entry]
      ,[Depr_ Starting Date (Custom 1)]
      ,[Depr_ Ending Date (Custom 1)]
      ,[Accum_ Depr_ % (Custom 1)]
      ,[Depr_ % this year (Custom 1)]
      ,[Property Class (Custom 1)]
      ,[No_ Series]
      ,[Tax Area Code]
      ,[Tax Liable]
      ,[Tax Group Code]
      ,[Use Tax]
      ,[VAT Bus_ Posting Group]
      ,[VAT Prod_ Posting Group]
      ,[Reversed]
      ,[Reversed by Entry No_]
      ,[Reversed Entry No_]
      ,0--[Dimension Set ID]
      ,[Employee No_]
      ,0--[Prepmt_ Diff_ Appln_ Entry No_]
      ,[Item No_]
      ,[Item Entry No_]
      ,[Value Entry No_]
      ,[Need Cost Posted to G_L]
      ,[Corr_ Value Entry No_]
      ,[Initial Acquisition]
      ,[FA Charge No_]
      ,[Depr_ Period Starting Date]
      ,[Depr_ Bonus]
      ,[Depr_ Bonus %]
      ,[Sales Gain Amount]
      ,[Sales Loss Amount]
      ,[Depr_ Amount w_o Normalization]
      ,[Depr_ Group Elimination]
      ,[Tax Difference Code]
      ,[Belonging to Manufacturing]
      ,[FA Type]
      ,[Depreciation Group]
      ,[Depr_ Bonus Recovery Date]
 FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$FA Ledger Entry]

 */