INSERT INTO [Bonava-Test].[dbo].[Bonava$Projects Budget Entry$2944687f-9cf8-4134-a24c-e21fb70a8b1a]
(
	[Entry No_],
    [Project Code],
    [Analysis Type],
    [Version Code],
    [Line No_],
    [Entry Type],
    [Description],
    [Description 2],
    [Amount],
    [Curency],
    [Currency Factor],
    [Amount (LCY)],
    [Date],
    [Transaction Type],
    [Create User],
    [Create Date],
    [Create Time],
    [Parent Entry],
    [Project Turn Code],
    [Code],
    [Contragent No_],
    [Agreement No_],
    [Without VAT],
    [Including VAT],
    [Contragent Name],
    [External Agreement No_],
    [Contragent Type],
    [Temp Line No_],
    [Close],
    [Shortcut Dimension 1 Code],
    [Shortcut Dimension 2 Code],
    [Building Turn],
    [Cost Code],
    [New Lines],
    [Not Run OnInsert],
    [Work Version],
    [Reserve],
    [Building Turn All],
    [Date Plan],
    [Write Off Amount],
    [NotVisible],
    [Without VAT (LCY)],
    [Problem Pmt_ Document],
    [Currency Rate]
)
SELECT
	[Entry No_],
    [Project Code],
    [Analysis Type],
    [Version Code],
    [Line No_],
    [Entry Type],
    [Description],
    [Description 2],
    [Amount],
    [Curency],
    [Currency Factor],
    [Amount (LCY)],
    [Date],
    [Transaction Type],
    [Create User],
    [Create Date],
    [Create Time],
    [Parent Entry],
    [Project Turn Code],
    [Code],
    [Contragent No_],
    [Agreement No_],
    [Without VAT],
    [Including VAT],
    [Contragent Name],
    [External Agreement No_],
    [Contragent Type],
    [Temp Line No_],
    [Close],
    [Shortcut Dimension 1 Code],
    [Shortcut Dimension 2 Code],
    [Building Turn],
    [Cost Code],
    [New Lines],
    [Not Run OnInsert],
    [Work Version],
    [Reserve],
    [Building Turn All],
    [Date Plan],
    [Write Off Amount],
    [NotVisible],
    [Without VAT (LCY)],
    [Problem Pmt_ Document],
    [Currency Rate]
FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$Projects Budget Entry]