delete from [dbo].[Bonava$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972]

insert into [dbo].[Bonava$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972]
(
      [No_]
      ,[Description]
      ,[Search Description]
      ,[Description 2]
      ,[FA Class Code]
      ,[FA Subclass Code]
      ,[Global Dimension 1 Code]
      ,[Global Dimension 2 Code]
      ,[Location Code]
      ,[FA Location Code]
      ,[Vendor No_]
      ,[Main Asset_Component]
      ,[Component of Main Asset]
      ,[Budgeted Asset]
      ,[Warranty Date]
      ,[Responsible Employee]
      ,[Serial No_]
      ,[Last Date Modified]
      ,[Blocked]
      ,[Picture]
      ,[Maintenance Vendor No_]
      ,[Under Maintenance]
      ,[Next Service Date]
      ,[Inactive]
      ,[No_ Series]
      ,[FA Posting Group]
      ,[Image]
      ,[Inventory Number]
      ,[Depreciation Code]
      ,[FA Type]
      ,[Depreciation Group]
      ,[Belonging to Manufacturing]
      ,[Status]
      ,[Factory No_]
      ,[Initial Release Date]
      ,[Status Document No_]
      ,[Passport No_]
      ,[Status Date]
      ,[Manufacturing Year]
      ,[Vehicle Identification Number]
      ,[Vehicle Model]
      ,[Vehicle Type]
      ,[Vehicle Reg_ No_]
      ,[Vehicle Capacity]
      ,[Vehicle Engine No_]
      ,[Vehicle Chassis No_]
      ,[Vehicle Passport Weight]
      ,[Run after Release Date]
      ,[Run after Renovation Date]
      ,[Vehicle Writeoff Date]
      ,[Vehicle Class]
      ,[Is Vehicle]
      ,[Last Renovation Date]
      ,[Manufacturer]
      ,[Undepreciable FA]
      ,[Operation Life (Months)]
      ,[Accrued Depr_ Amount]
      ,[CD No_]
      ,[Assessed Tax Code]
      ,[FA Type for Taxation]
      ,[Distributed Asset]
      ,[UGSS Asset]
      ,[OKATO Code]
      ,[Book Value per Share]
      ,[Property Type]
      ,[Tax Amount Paid Abroad]
      ,[Tax Difference Code]
      ,[Created by FA No_]
)
select 
      [No_]
      ,[Description]
      ,[Search Description]
      ,[Description 2]
      ,[FA Class Code]
      ,[FA Subclass Code]
      ,[Global Dimension 1 Code]
      ,[Global Dimension 2 Code]
      ,[Location Code]
      ,[FA Location Code]
      ,[Vendor No_]
      ,[Main Asset_Component]
      ,[Component of Main Asset]
      ,[Budgeted Asset]
      ,[Warranty Date]
      ,[Responsible Employee]
      ,[Serial No_]
      ,[Last Date Modified]
      ,[Blocked]
      ,[Picture]
      ,[Maintenance Vendor No_]
      ,[Under Maintenance]
      ,[Next Service Date]
      ,[Inactive]
      ,[No_ Series]
      ,[FA Posting Group]
      ,'00000000-0000-0000-0000-000000000000' --[Image]
      ,[Inventory Number]
      ,[Depreciation Code]
      ,[FA Type]
      ,[Depreciation Group]
      ,[Belonging to Manufacturing]
      ,[Status]
      ,[Factory No_]
      ,[Initial Release Date]
      ,[Status Document No_]
      ,[Passport No_]
      ,[Status Date]
      ,[Manufacturing Year]
      ,[Vehicle Identification Number]
      ,[Vehicle Model]
      ,[Vehicle Type]
      ,[Vehicle Reg_ No_]
      ,[Vehicle Capacity]
      ,[Vehicle Engine No_]
      ,[Vehicle Chassis No_]
      ,[Vehicle Passport Weight]
      ,[Run after Release Date]
      ,[Run after Renovation Date]
      ,[Vehicle Writeoff Date]
      ,[Vehicle Class]
      ,[Is Vehicle]
      ,[Last Renovation Date]
      ,[Manufacturer]
      ,[Undepreciable FA]
      ,[Operation Life (Months)]
      ,[Accrued Depr_ Amount]
      ,'' --[CD No_]
      ,[Assessed Tax Code]
      ,[FA Type for Taxation]
      ,[Distributed Asset]
      ,[UGSS Asset]
      ,[oktmo code]--[OKATO Code]
      ,[Book Value per Share]
      ,[Property Type]
      ,[Tax Amount Paid Abroad]
      ,[Tax Difference Code]
      ,[Created by FA No_]
FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$Fixed Asset]
WHERE [Blocked]=0


--select * from [dbo].[Bonava$Fixed Asset$437dbf0e-84ff-417a-965d-ed2bb9650972]
