delete from [dbo].[Bonava$FA Depreciation Book$437dbf0e-84ff-417a-965d-ed2bb9650972]

insert into [dbo].[Bonava$FA Depreciation Book$437dbf0e-84ff-417a-965d-ed2bb9650972]
(      
	  [FA No_]
      ,[Depreciation Book Code]
      ,[Depreciation Method]
      ,[Depreciation Starting Date]
      ,[Straight-Line _]
      ,[No_ of Depreciation Years]
      ,[No_ of Depreciation Months]
      ,[Fixed Depr_ Amount]
      ,[Declining-Balance _]
      ,[Depreciation Table Code]
      ,[Final Rounding Amount]
      ,[Ending Book Value]
      ,[FA Posting Group]
      ,[Depreciation Ending Date]
      ,[Acquisition Date]
      ,[G_L Acquisition Date]
      ,[Disposal Date]
      ,[Last Acquisition Cost Date]
      ,[Last Depreciation Date]
      ,[Last Write-Down Date]
      ,[Last Appreciation Date]
      ,[Last Custom 1 Date]
      ,[Last Custom 2 Date]
      ,[Last Salvage Value Date]
      ,[FA Exchange Rate]
      ,[Fixed Depr_ Amount below Zero]
      ,[Last Date Modified]
      ,[First User-Defined Depr_ Date]
      ,[Use FA Ledger Check]
      ,[Last Maintenance Date]
      ,[Depr_ below Zero _]
      ,[Projected Disposal Date]
      ,[Projected Proceeds on Disposal]
      ,[Depr_ Starting Date (Custom 1)]
      ,[Depr_ Ending Date (Custom 1)]
      ,[Accum_ Depr_ _ (Custom 1)]
      ,[Depr_ This Year _ (Custom 1)]
      ,[Property Class (Custom 1)]
      ,[Description]
      ,[Main Asset_Component]
      ,[Component of Main Asset]
      ,[FA Add_-Currency Factor]
      ,[Use Half-Year Convention]
      ,[Use DB_ First Fiscal Year]
      ,[Temp_ Ending Date]
      ,[Temp_ Fixed Depr_ Amount]
      ,[Ignore Def_ Ending Book Value]
      ,[Default FA Depreciation Book]
      ,[Initial Acquisition]
      ,[Depr_ Bonus _]
)
select
	  [FA No_]
      ,[Depreciation Book Code]
      ,[Depreciation Method]
      ,[Depreciation Starting Date]
      ,[Straight-Line %]
      ,[No_ of Depreciation Years]
      ,[No_ of Depreciation Months]
      ,[Fixed Depr_ Amount]
      ,[Declining-Balance %]
      ,[Depreciation Table Code]
      ,[Final Rounding Amount]
      ,[Ending Book Value]
      ,[FA Posting Group]
      ,[Depreciation Ending Date]
      ,[Acquisition Date]
      ,[G_L Acquisition Date]
      ,[Disposal Date]
      ,[Last Acquisition Cost Date]
      ,[Last Depreciation Date]
      ,[Last Write-Down Date]
      ,[Last Appreciation Date]
      ,[Last Custom 1 Date]
      ,[Last Custom 2 Date]
      ,[Last Salvage Value Date]
      ,[FA Exchange Rate]
      ,[Fixed Depr_ Amount below Zero]
      ,[Last Date Modified]
      ,[First User-Defined Depr_ Date]
      ,[Use FA Ledger Check]
      ,[Last Maintenance Date]
      ,[Depr_ below Zero %]
      ,[Projected Disposal Date]
      ,[Projected Proceeds on Disposal]
      ,[Depr_ Starting Date (Custom 1)]
      ,[Depr_ Ending Date (Custom 1)]
      ,[Accum_ Depr_ % (Custom 1)]
      ,[Depr_ This Year % (Custom 1)]
      ,[Property Class (Custom 1)]
      ,[Description]
      ,[Main Asset_Component]
      ,[Component of Main Asset]
      ,[FA Add_-Currency Factor]
      ,[Use Half-Year Convention]
      ,0--[Use DB_ First Fiscal Year]
      ,[Temp_ Ending Date]
      ,[Temp_ Fixed Depr_ Amount]
      ,[Ignore Def_ Ending Book Value]
      ,''--[Default FA Depreciation Book]
      ,[Initial Acquisition]
      ,[Depr_ Bonus %]

  FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$FA Depreciation Book]


  --select *  FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$FA Depreciation Book]